blank_issues_enabled: true
contact_links:
  - name: Translation issue or contribution
    url: https://github.com/GDQuest/learn-gdscript-translations/issues/new
    about: Report translation problems or help translate the app into your language. All translation work happens in this separate repository.
  - name: Questions and help
    url: https://discord.gg/87NNb3Z
    about: Ask questions and get help from the community in our Discussions section.
