name: "[ BuildGodot ] â†’ gh-pages"

on:
  workflow_call:
    inputs:
      sub_build_path:
        required: false
        type: string
        default: ""
      watermark:
        required: false
        type: string
        default: $GITHUB_REPOSITORY:$GITHUB_WORKFLOW:$GITHUB_REF_NAME:$GITHUB_SHA
      override_file:
        required: false
        type: string
        default: ""

env:
  GODOT_VERSION: 3.4.1

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Install Necessary Software
        run: |
          apt-get update && apt-get install -y --no-install-recommends sed 
      - name: Override Configuration
        run: |
          cp ${{override_file}} override.cfg || echo "no config override to copy"
      - name: Web Build
        run: |
          mkdir -v -p build/web${{inputs.sub_build_path}}/web && \
          godot -v --export "HTML5" build/web${{inputs.sub_build_path}}/index.html || true && \
          echo "built godot"
      - name: Copy static files
        run: |
          cp -r html_export/static/* build/web${{inputs.sub_build_path}} && \
          echo "copied files"
      - name: Add Git Hash to build
        run: |
          cd build/web${{inputs.sub_build_path}}
          sed -i "s@>branch and commit hash<@>${{ inputs.watermark }}<@" index.html && \
          echo "added commit hash to index.html" || echo "failed to add the commit hash"
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
      - name: Install rsync ğŸ“š
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages ğŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/web
          clean: false